language: cpp
os: linux
dist:
  - xenial
  - bionic
compiler: gcc

git:
  depth: 1

install:
  - sudo apt-get install -qq qt5-default

script:
  - NCPU=$(nproc)
  - echo "Will compile on $NCPU CPUs"

  - mkdir -p build && cd build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release
  - make -j$NCPU package
  - cd ../

  - mv build/*.deb .
  - dpkg -c *.deb

# deploy:
#   provider: releases
#   api_key:
#     secure: MYO3XLtpEgrb9cXmOM9CfKOxyJrsNVONDrz/1KLd0RE+aaRKtPN0MFaxUKJgRj6RbXYIoSA8EFfJojV3uDk2PnjKbYxzaTN8cVn8NocMXtdAt6vu6sB4KdyUZMfDTDUT0SOIB6V4+DpvcBfP9XXP1sV8tlFlsYTbfLHSW3sAkH0dHyEN3U6W0ArfZyX6SrQEpQjUHhc4/JsHGbYF/8Pv9Mbhha51rX6RugV0732fvibicToAJ/6hB2G/x3gLFK+fjvSeodpqNEnSaDwz0w/BH4ErCqx+YHGQGOfO+BuK76wcx1h+ObGOnDAH+WFlfvo19yP5+zvzff3DcXDeHMyjYPQl8NX2JXfYVyNJ2CWTZ4GdMtfrgsYN96OQUiFK26omBXIiuj5IsfPL+vP/mXtht5iagEsew5qy1dJeqMHv+oz+EztAqnRw1rwcAVLwO48rh42d5NvDvtBMb4xn0axpxLCZdr2BxWM8xfSDN7iAXYmpbGs6l0a2BOOyLbS35Qvyne+Le//glTq6pM2zZfv4BcJTXXDX7u7zE8Nqn/ZZty3FNEtfPqH97rAxPaBe6FJej38WHcsQwsfczTAMjIfnnfpVqhjpIQyukG+aZYcMS49lMKT4VU+iNNLOAHMUH4c1oQr2LvqVY+ferFbdI55IEJSwBoAzOjL/x4NEryNmQ0E=
#   file_glob: true
#   file: "*.deb"
#   skip_cleanup: true
#   on:
#     tags: true
